### ISSUE TITLE
Can you show some experiment result in your project?

### ISSUE THREAD

**Issue by wodaka** [sam-nayak/SynthNet#11]

**Comment by wodaka** [comment]
The parameter shape of FuzzyLayer seems different from the paper.
 In your code, the input shape is [batch, 32, 32 * 3] for the color image. So the the fuzzy_membership_layers include 32 Fuzzylayers，in each Fuzzylayer, the shape u_i is [32 * 3, 100]，and the shape delta_i is [32 * 3, 100], 100 is output dimension. 
But in the paper, the input should be one dimension vector, suppose it is [batch, 32], after the membership function, the vector dimention should be [batch, num_classes, 32], the number of membership function is set as num_classes, the number of u_i is num_classes, and the same as delta_i. After the fuzzyRule layer, the vector dimension should be [batch, num_classes]?  I dont know if the comprehension of mine is correct?

**Comment by qianhuiliu** [comment]
Hi, I have the same question, do you know the answer?
